### ISSUE TITLE
A função brMinisterioSaude não está encontrando os dados...

### ISSUE THREAD

**Issue by brunocp76** [Freguglia/datacovidbr#2]
Aparentemente o Ministério da Saúde mudou o caminho da disponibilização dos dados.

Eu gostaria de poder ajudar a resolver o problema, mas acho que (ainda) não tenho os conhecimentos para isso.

**Comment by Freguglia** [comment]
Olá @brunocp76 !

Obrigado por avisar. O problema era que o arquivo disponibilizado passou a ser um `.zip` com um `.csv` dentro. Eu já havia automatizado a leitura para os casos do arquivo ser `.csv` e `.xlsx,` mas antes não haviam usado `.zip` em nenhum momento. 

Já corrigi o código no repositório, acredito que já esteja funcionando novamente. Vou só esperar os testes no Travis para confirmar.
